# Predicting Salaries based on years of experience using Simple Linear Regression

# What is simple linear regression? 
Simple linear regression is a statistical method that helps us in summarizing and studying the relationship between two continuous or interval variables. One of the variable, oftened termes as 'x', is the one that is independent. It is also called as the explanatory or predictor variabe. The other variable, often termed as 'y', is the one which is dependent on 'x'. For this reason, it is called as a dependent, outcome or response variable. We will simply refer 'x' as the independent variable and 'y' as the dependent variable. Finally, it's called a "linear" regression as it tries to define a linear relationship between x and y. We will go through the following business problem and try to solve it using simple linear regression.

# Business Problem:
We have a information of 30 employees. The information includes 'salary' and 'years of experience' of the employees. We want to study the relationship between these two variables and come up with a model that best defines this relationship. Further, this model can be used to predict salary of employee when their 'years of experience' is given. So, lets gets started!!

In [1]:
# Importing required libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# Importing the dataset
data = pd.read_csv('C:/Projects/Datasets/SimpleLinearRegression_Salary_Data.csv')
data.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [3]:
# Creating tow different variables (x and y) out of the dataset
x = data.iloc[:,0].values
y = data.iloc[:,-1].values
x
y

array([  39343.,   46205.,   37731.,   43525.,   39891.,   56642.,
         60150.,   54445.,   64445.,   57189.,   63218.,   55794.,
         56957.,   57081.,   61111.,   67938.,   66029.,   83088.,
         81363.,   93940.,   91738.,   98273.,  101302.,  113812.,
        109431.,  105582.,  116969.,  112635.,  122391.,  121872.])

In [4]:
# Lets see if we got that right
print(x)
print(type(x))

[  1.1   1.3   1.5   2.    2.2   2.9   3.    3.2   3.2   3.7   3.9   4.
   4.    4.1   4.5   4.9   5.1   5.3   5.9   6.    6.8   7.1   7.9   8.2
   8.7   9.    9.5   9.6  10.3  10.5]
<class 'numpy.ndarray'>


We can see that this variable, x, has all the data points that refer to years of experience of the employees. This is the independent variable. This variable is a numpy array.

In [5]:
print(y)
print(type(y))

[  39343.   46205.   37731.   43525.   39891.   56642.   60150.   54445.
   64445.   57189.   63218.   55794.   56957.   57081.   61111.   67938.
   66029.   83088.   81363.   93940.   91738.   98273.  101302.  113812.
  109431.  105582.  116969.  112635.  122391.  121872.]
<class 'numpy.ndarray'>


We can see that this variable, y, has all the data points that refer to salaries of the employees . This is the dependent variable. This variable is a numpy array.

Our dataset is small and not that complex. It is a clean dataset, meaning that we don't have to pre-process our data.

## Splitting dataset into train and test data sets
We generally split our data set into 2 parts. One is the training set which is used to analyze the relationship between the variables and build a model. The other one is the test set which is used to test our model and assess accuracy.

Now, to split our dataset, we'll be making use of a function 'train_test_split'. This function is a part of the library sklearn.cross_validation. So let's import this function and then use it to split our dataset.

In [9]:
# Importing the necessary library for train-test split
from sklearn.cross_validation import train_test_split

# Splitting into 2:1 ratio, meaning that the test set will have 1/3 of the data and train 2/3
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 1/3)
x_train, x_test, y_train, y_test

(array([  3.7,   4.5,   4. ,   9.6,   4.9,   6.8,   3.9,  10.5,   9. ,
          5.9,   3.2,   5.1,   8.7,  10.3,   7.9,   1.5,   4. ,   2. ,
          1.3,   8.2]),
 array([ 3.2,  1.1,  3. ,  2.9,  7.1,  5.3,  2.2,  9.5,  4.1,  6. ]),
 array([  57189.,   61111.,   56957.,  112635.,   67938.,   91738.,
          63218.,  121872.,  105582.,   81363.,   54445.,   66029.,
         109431.,  122391.,  101302.,   37731.,   55794.,   43525.,
          46205.,  113812.]),
 array([  64445.,   39343.,   60150.,   56642.,   98273.,   83088.,
          39891.,  116969.,   57081.,   93940.]))

Our train and test datasets are ready now. Now, lets proceed with buiding the model based on the training datased

## Building the Linear Regression Model
But before that, an important note
"We will not be scaling(standardizing/normalizing) our data as the linear regression class, that we'll be using, does that implicitly"

There's a class within the library sklearn.linear_model by the name "LinearRegression". This is the class that we'll be using to build our class. Let's now import the same.

In [7]:
# Importing LinearRegression class
from sklearn.linear_model import LinearRegression

Let's now instantiate our "regressor" object that we'll use to study the relationship between x and y(to be specific, x_train and y_train)

In [8]:
# Creating the regressor
regressor = LinearRegression()